//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\Documents\VCProjects\DCPlusPlus\DCPlusPlus.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_TRAY_QUIT                   102
#define IDC_TRAY_SHOW                   103
#define IDC_COPY_HUB                    104
#define ID_VIEW_TRANSFER_VIEW           105
#define IDD_GENERALPAGE                 107
#define IDD_NETWORKPAGE                 108
#define IDR_MAINFRAME                   128
#define IDR_HUB                         129
#define IDC_HUBLIST                     131
#define IDC_SERVER                      133
#define IDC_EXTERNAL_IP                 133
#define IDC_FILES                       135
#define IDB_FOLDERS                     206
#define IDB_ARROWS                      207
#define IDD_LINE                        208
#define IDB_USERS                       209
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_UPLOADPAGE                  212
#define IDB_TOOLBAR                     213
#define IDD_APPEARANCEPAGE              214
#define IDR_PUBLICHUBS                  215
#define IDR_SEARCH                      216
#define IDR_FAVORITES                   217
#define IDR_PRIVATE                     218
#define IDR_DIRECTORY                   219
#define IDR_NOTEPAD                     220
#define IDB_TOOLBAR20                   221
#define IDR_QUEUE                       222
#define IDR_SPY                         223
#define IDD_FAVORITEHUB                 224
#define IDR_USERS                       225
#define IDD_LOGPAGE                     226
#define IDI_MAGNET                      229
#define IDD_USER_COMMAND                230
#define IDR_FINISHED_DL                 231
#define IDR_FINISHED_UL                 232
#define IDR_ADLSEARCH                   233
#define IDD_ADLS_PROPERTIES             234
#define IDB_TOOLBAR20_HOT               235
#define IDD_UCPAGE                      236
#define IDR_NET_STATS                   237
#define IDD_MAGNET                      238
#define IDD_HASH_PROGRESS               239
#define IDD_FAVORITE_DIRSPAGE           240
#define IDD_HUB_LIST                    241
#define IDD_APPEARANCE2PAGE             242
#define IDD_ADVANCED3PAGE               243
#define IDD_WINDOWSPAGE                 244
#define IDD_QUEUEPAGE                   245
#define IDD_CERTIFICATESPAGE            246
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_HELP_CONTENTS               1004
#define IDC_CONNECTION                  1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1007
#define IDC_FIREWALL_PASSIVE            1008
#define IDC_PORT_TCP                    1009
#define IDC_DIRECTORIES                 1010
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_TOTAL                       1013
#define IDC_SLOTS                       1014
#define IDC_SLOTSPIN                    1015
#define IDC_TRANSFERS                   1016
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1019
#define IDC_RESULTS                     1020
#define IDC_LINE                        1021
#define IDC_DOWNLOADDIRTO               1022
#define IDC_PRIVATEMESSAGE              1023
#define IDC_VERSION                     1024
#define IDC_GETLIST                     1025
#define IDC_ROLLBACK                    1026
#define IDC_EDIT                        1027
#define IDC_NOTEPAD                     1028
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_SELWINCOLOR                 1030
#define IDC_SELTEXT                     1031
#define IDC_COLOREXAMPLE                1032
#define IDC_SHAREHIDDEN                 1033
#define IDC_QUEUE                       1034
#define IDC_HUBNICK                     1035
#define IDC_PREVIEW                     1036
#define IDC_HUBPASS                     1037
#define IDC_NEWFAV                      1038
#define IDC_HUBNAME                     1039
#define IDC_SOURCE_TYPE                 1040
#define IDC_SIZE_TYPE                   1041
#define IDC_HUBDESCR                    1042
#define IDC_HUBADDR                     1043
#define IDC_GRANTSLOT                   1044
#define IDC_FORCE                       1045
#define IDC_BUFFERSIZE                  1046
#define IDC_LANGUAGE                    1047
#define IDC_BROWSE                      1048
#define IDC_SETTINGS_LIST_CONFIG        1049
#define IDC_THANKS                      1050
#define IDC_DOWNLOADS                   1051
#define IDC_SLOTSSPIN                   1052
#define IDC_MAXSPEED                    1053
#define IDC_SPEEDSPIN                   1054
#define IDC_FAVUSERS                    1055
#define IDC_PROXY                       1056
#define IDC_ADD_TO_FAVORITES            1057
#define IDC_LOG_MAIN_CHAT               1058
#define IDC_LOG_PRIVATE_CHAT            1059
#define IDC_HELP_HOMEPAGE               1060
#define IDC_LOG_DOWNLOADS               1061
#define IDC_HELP_DOWNLOADS              1062
#define IDC_LOG_UPLOADS                 1063
#define IDC_HELP_REPORT_BUG             1064
#define IDC_LOG_DIRECTORY               1065
#define IDC_HELP_REQUEST_FEATURE        1066
#define IDC_BROWSE_LOG                  1067
#define IDC_HELP_DISCUSS                1068
#define IDC_HELP_HELP_FORUM             1069
#define IDC_HELP_FAQ                    1070
#define IDC_SEARCH_SPY                  1071
#define IDC_LATEST                      1072
#define IDC_PRIVATE_MESSAGE_BEEP        1073
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1074
#define IDC_MIN_UPLOAD_SPEED            1075
#define IDC_SETTINGS_TYPE               1076
#define IDC_MIN_UPLOAD_SPIN             1077
#define IDC_CHEVRON                     1078
#define IDC_OPEN_FILE_LIST              1079
#define IDC_TOTALS                      1080
#define IDC_SEARCH                      1081
#define IDC_RATIO                       1082
#define IDC_POST_DOWNLOAD               1084
#define IDC_CLOSE_WINDOW                1085
#define IDC_POST_UPLOAD                 1086
#define IDC_FIND                        1087
#define IDC_MAIN_CHAT                   1088
#define IDC_NEXT                        1089
#define IDC_PRIVATE_CHAT                1090
#define IDC_FINISHED                    1091
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1092
#define IDC_BROWSETEMPDIR               1093
#define IDC_SOCKS_RESOLVE               1094
#define IDC_REMOVEALL                   1095
#define IDC_HELP_DONATE                 1096
#define IDC_SOCKS5                      1097
#define IDC_SOCKS_SERVER                1098
#define IDC_SOCKS_PORT                  1099
#define IDC_SOCKS_USER                  1100
#define IDC_SOCKS_PASSWORD              1101
#define IDC_FREESLOTS                   1102
#define IDC_HELP_TRANSLATIONS           1103
#define IDC_COPY_NICK                   1104
#define IDC_ADVANCED_BOOLEANS           1105
#define IDC_ADD_MENU                    1106
#define IDC_MOVE                        1107
#define IDC_REMOVE_MENU                 1108
#define IDC_MENU_ITEMS                  1109
#define IDC_CHANGE_MENU                 1110
#define IDC_NAME                        1111
#define IDC_COMMAND                     1112
#define IDC_HUB                         1113
#define IDC_USER_CMD_PREVIEW            1114
#define IDC_APPEARANCE_BOOLEANS         1115
#define IDC_DEFAULT_AWAY_MESSAGE        1116
#define IDC_MAX_TAB_ROWS                1117
#define IDC_CLOSE_DISCONNECTED          1118
#define IDC_OPEN_FOLDER                 1119
#define IDC_OPEN_FILE                   1120
#define IDC_FILE_ADL_SEARCH             1121
#define IDC_ADLLIST                     1122
#define IDC_MOVE_UP                     1123
#define IDC_MOVE_DOWN                   1124
#define IDC_HUBUSERDESCR                1125
#define IDC_FINISHED_UL                 1126
#define IDC_SEARCH_STRING               1127
#define IDC_DEST_DIR                    1128
#define IDC_IS_ACTIVE                   1129
#define IDC_MIN_FILE_SIZE               1130
#define IDC_MAX_FILE_SIZE               1131
#define IDC_AUTOQUEUE                   1132
#define IDC_GO_TO_DIRECTORY             1133
#define IDC_MATCH_QUEUE                 1134
#define IDC_HELP_CHANGELOG              1135
#define IDC_VIEW_AS_TEXT                1136
#define IDC_PAGE                        1137
#define IDC_NET_STATS                   1138
#define IDC_SETTINGS_PERSONAL_INFORMATION 1139
#define IDC_SETTINGS_NICK               1140
#define IDC_SETTINGS_EMAIL              1141
#define IDC_SETTINGS_DESCRIPTION        1142
#define IDC_SETTINGS_UPLOAD_LINE_SPEED  1143
#define IDC_SETTINGS_INCOMING           1144
#define IDC_SETTINGS_IP                 1145
#define IDC_SETTINGS_PORT_TCP           1146
#define IDC_SETTINGS_SOCKS5_IP          1147
#define IDC_SETTINGS_SOCKS5_PORT        1148
#define IDC_SETTINGS_SOCKS5_USERNAME    1149
#define IDC_SETTINGS_SOCKS5_PASSWORD    1150
#define IDC_SETTINGS_DIRECTORIES        1151
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1152
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1153
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1154
#define IDC_SETTINGS_DOWNLOADS_MAX      1155
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1156
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1157
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1158
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1159
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1160
#define IDC_SETTINGS_SHARED_DIRECTORIES 1161
#define IDC_SETTINGS_SHARE_SIZE         1162
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1163
#define IDC_SETTINGS_UPLOADS_SLOTS      1164
#define IDC_SETTINGS_COLORS             1165
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1166
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1167
#define IDC_SETTINGS_LANGUAGE_FILE      1168
#define IDC_SETTINGS_REQUIRES_RESTART   1169
#define IDC_SETTINGS_LOGGING            1170
#define IDC_SETTINGS_LOG_DIR            1171
#define IDC_SETTINGS_SOUNDS             1172
#define IDC_SETTINGS_ADVANCED           1173
#define IDC_SETTINGS_ROLLBACK           1174
#define IDC_SETTINGS_WRITE_BUFFER       1176
#define IDC_SETTINGS_MAX_TAB_ROWS       1177
#define IDC_SETTINGS_USER_MENU          1178
#define IDC_SETTINGS_KB                 1179
#define IDC_SETTINGS_B                  1180
#define IDC_SETTINGS_KBPS               1181
#define IDC_ADD_AS_FAVORITE             1182
#define IDC_SETTINGS_SEPARATOR          1183
#define IDC_ADLSP_SEARCH                1184
#define IDC_ADLSP_TYPE                  1185
#define IDC_ADLSP_SIZE_MIN              1186
#define IDC_ADLSP_SIZE_MAX              1187
#define IDC_ADLSP_UNITS                 1188
#define IDC_ADLSP_DESTINATION           1189
#define IDC_SETTINGS_RAW                1190
#define IDC_SETTINGS_CHAT               1191
#define IDC_SETTINGS_PM                 1192
#define IDC_SETTINGS_HUB_MENU           1193
#define IDC_SETTINGS_SEARCH_MENU        1194
#define IDC_SETTINGS_CONTEXT            1195
#define IDC_SETTINGS_PARAMETERS         1196
#define IDC_SETTINGS_NAME               1197
#define IDC_SETTINGS_COMMAND            1198
#define IDC_SETTINGS_HUB                1199
#define IDC_SETTINGS_TO                 1200
#define IDC_RESULT                      1201
#define IDC_REFRESH_FILE_LIST           1202
#define IDC_SETTINGS_ONCE               1203
#define IDC_OPEN_DOWNLOADS              1204
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1205
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1206
#define IDC_SETTINGS_FORMAT             1207
#define IDC_SEARCH_HISTORY              1208
#define IDC_SETTINGS_SEARCH_HISTORY     1209
#define IDC_LOG_SYSTEM                  1211
#define IDC_SETTINGS_HASH_SPEED         1213
#define IDC_MAX_HASH_SPEED              1214
#define IDC_SETTINGS_MAX_HASH_SPEED     1215
#define IDC_SETTINGS_MBS                1216
#define IDC_SETTINGS_GET_USER_COUNTRY   1217
#define IDC_LOG_STATUS_MESSAGES         1218
#define IDC_TTH                         1219
#define IDC_BITZI_LOOKUP                1220
#define IDC_COPY_MAGNET                 1221
#define IDC_MAGNET_QUEUE                1222
#define IDC_MAGNET_SEARCH               1223
#define IDC_MAGNET_REMEMBER             1224
#define IDC_MAGNET_HASH                 1225
#define IDC_MAGNET_NAME                 1226
#define IDC_MAGNET_NOTHING              1227
#define IDC_MAGNET_DISP_NAME            1228
#define IDC_MAGNET_DISP_HASH            1229
#define IDC_MAGNET_TEXT                 1230
#define IDC_SETTINGS_TIME_STAMPS_FORMAT 1231
#define IDC_TIME_STAMPS_FORMAT          1232
#define IDC_SETTINGS_ONLY_HASHED        1233
#define IDC_HASH_PROGRESS               1234
#define IDC_HASH_INDEXING               1235
#define IDC_FILES_PER_HOUR              1236
#define IDC_HASH_SPEED                  1237
#define IDC_FILES_LEFT                  1238
#define IDC_TIME_LEFT                   1239
#define IDC_BYTES_LEFT                  1240
#define IDC_STATISTICS                  1241
#define IDC_CURRENT_FILE                1242
#define IDC_FH_HUB                      1243
#define IDC_FH_IDENT                    1244
#define IDC_FH_NAME                     1245
#define IDC_FH_ADDRESS                  1246
#define IDC_FH_HUB_DESC                 1247
#define IDC_FH_NICK                     1248
#define IDC_FH_PASSWORD                 1249
#define IDC_FH_USER_DESC                1250
#define IDC_USER_CMD_OPEN_HELP          1251
#define IDC_SETTINGS_FAVORITE_DIRECTORIES 1252
#define IDC_FAVORITE_DIRECTORIES        1253
#define IDC_PUB_LIST_CONFIG             1254
#define IDC_PUB_LIST_DROPDOWN           1255
#define IDC_LIST_ADD                    1256
#define IDC_LIST_EDIT_BOX               1257
#define IDC_LIST_UP                     1258
#define IDC_LIST_DOWN                   1259
#define IDC_LIST_REMOVE                 1260
#define IDC_LIST_DESC                   1261
#define IDC_LIST_LIST                   1262
#define IDC_RENAME                      1263
#define IDC_LIST_EDIT                   1264
#define IDC_OPEN_OWN_LIST               1265
#define IDC_PORT_UDP                    1266
#define IDC_SETTINGS_PORT_UDP           1267
#define IDC_DOWNLOAD_FILE               1268
#define IDC_UPLOAD_FILE                 1269
#define IDC_PRIVATE_CHAT_FILE           1270
#define IDC_STATUS_FILE                 1271
#define IDC_MAIN_CHAT_FILE              1272
#define IDC_LOG_FORMAT                  1273
#define IDC_LOG_FILE                    1274
#define IDC_LOG_OPTIONS                 1275
#define IDC_SETTINGS_FILE_NAME          1276
#define IDC_ONLYTTH                     1277
#define IDC_SETTINGS_FILELIST_MENU      1278
#define IDC_SHOW_LAST_LINES_LOG         1279
#define IDC_SETTINGS_PM_HISTORY         1280
#define IDC_SEARCH_HISTORY_SPIN         1281
#define IDC_PURGE                       1282
#define IDC_SET_MINISLOT_SIZE           1283
#define IDC_SETTINGS_TEXT_MINISLOT      1284
#define IDC_SETTINGS_KB2                1285
#define IDC_BIND_ADDRESS                1286
#define IDC_SETTINGS_BIND_ADDRESS       1287
#define IDC_WINDOWS_STARTUP             1288
#define IDC_SETTINGS_AUTO_OPEN          1289
#define IDC_WINDOW_OPTIONS              1290
#define IDC_WINDOWS_OPTIONS             1290
#define IDC_SETTINGS_WINDOWS_OPTIONS    1291
#define IDC_HELP_GEOIPFILE              1292
#define IDC_FIREWALL_UPNP               1293
#define IDC_DIRECT                      1294
#define IDC_FIREWALL_NAT                1295
#define IDC_SETTINGS_OUTGOING           1296
#define IDC_DIRECT_OUT                  1297
#define IDC_OVERRIDE                    1298
#define IDC_SETTINGS_PORTS              1299
#define IDC_PRIO_HIGHEST_SIZE           1300
#define IDC_PRIO_HIGH_SIZE              1301
#define IDC_PRIO_NORMAL_SIZE            1302
#define IDC_PRIO_LOW_SIZE               1303
#define IDC_SETTINGS_PRIO_HIGHEST       1304
#define IDC_SETTINGS_PRIO_HIGH          1305
#define IDC_SETTINGS_PRIO_NORMAL        1306
#define IDC_SETTINGS_PRIO_LOW           1307
#define IDC_SETTINGS_KB3                1308
#define IDC_SETTINGS_KB4                1309
#define IDC_SETTINGS_KB5                1310
#define IDC_SETTINGS_KB6                1311
#define IDC_SETTINGS_AUTOPRIO           1312
#define IDC_BOLD_BOOLEANS               1313
#define IDC_SETTINGS_BOLD_CONTENTS      1314
#define IDC_SETTINGS_CONFIRM_OPTIONS    1315
#define IDC_CONFIRM_OPTIONS             1316
#define IDC_SOCKET_IN_BUFFER            1317
#define IDC_EDIT2                       1318
#define IDC_SOCKET_OUT_BUFFER           1318
#define IDC_SSL_CERTIFICATE_FILE        1318
#define IDC_TLS_CERTIFICATE_FILE        1318
#define IDC_SETTINGS_SOCKET_OUT_BUFFER  1319
#define IDC_SETTINGS_SOCKET_IN_BUFFER   1320
#define IDC_CHECK1                      1321
#define IDC_AUTODROP_SPEED              1350
#define IDC_AUTODROP_INTERVAL           1351
#define IDC_AUTODROP_ELAPSED            1352
#define IDC_AUTODROP_INACTIVITY         1353
#define IDC_AUTODROP_MINSOURCES         1354
#define IDC_AUTODROP_FILESIZE           1355
#define IDC_SETTINGS_AUTODROP_SPEED     1356
#define IDC_SETTINGS_AUTODROP_INTERVAL  1357
#define IDC_SETTINGS_AUTODROP_ELAPSED   1358
#define IDC_SETTINGS_AUTODROP_INACTIVITY 1359
#define IDC_SETTINGS_AUTODROP_MINSOURCES 1360
#define IDC_SETTINGS_AUTODROP_FILESIZE  1361
#define IDC_SETTINGS_BPS                1362
#define IDC_SETTINGS_S1                 1363
#define IDC_SETTINGS_S2                 1364
#define IDC_SETTINGS_S3                 1365
#define IDC_SETTINGS_KB7                1366
#define IDC_SETTINGS_AUTODROP           1367
#define IDC_OTHER_QUEUE_OPTIONS         1400
#define IDC_SETTINGS_OTHER_QUEUE_OPTIONS 1401
#define IDC_SETTINGS_PRIO_LOWEST        1402
#define IDC_SETTINGS_AUTODROP_ALL       1403
#define IDC_SETTINGS_AUTODROP_DISCONNECT 1404
#define IDC_SETTINGS_AUTODROP_FILELISTS 1405
#define IDC_SETTINGS_MEBIBYES           1406
#define IDC_SETTINGS_MEBIBITS           1406
#define IDC_FILELIST_DIFF               1407
#define IDC_COPY_FILENAME               1408
#define IDC_MAX_FILELIST_SIZE           1409
#define IDC_SETTINGS_MAX_FILELIST_SIZE  1410
#define IDC_SETTINGS_MB                 1411
#define IDC_SYSTEM_LOG                  1412
#define IDC_SSL_PRIVATE_KEY_FILE        1414
#define IDC_TLS_PRIVATE_KEY_FILE        1414
#define IDC_SSL_TRUSTED_CERTIFICATES_PATH 1415
#define IDC_TLS_TRUSTED_CERTIFICATES_PATH 1415
#define IDC_CLIENT_ID                   1416
#define IDC_PRIVATE_ID                  1416
#define IDC_AUTO_REFRESH_TIME           1419
#define IDC_SETTINGS_AUTO_REFRESH_TIME  1420
#define IDC_AUTO_SEARCH_LIMIT           1421
#define IDC_SSL_OPTIONS                 1421
#define IDC_TLS_OPTIONS                 1421
#define IDC_SETTINGS_AUTO_SEARCH_LIMIT  1422
#define IDC_CLOSE_ALL_PM                1423
#define IDC_CLOSE_ALL_OFFLINE_PM        1424
#define IDC_CLOSE_ALL_DIR_LIST          1425
#define IDC_CLOSE_ALL_SEARCH_FRAME      1426
#define IDC_BROWSELIST                  3000
#define IDC_REMOVE_SOURCE               3500
#define IDC_PM                          4000
#define IDC_READD                       4500
#define IDC_DOWNLOAD_TARGET             5000
#define IDC_DOWNLOAD_TARGET_DIR         5500
#define IDC_SELECT_WINDOW               6000
#define IDC_USER_COMMAND                6500
#define IDC_VIEW_WAITING_USERS          6628
#define IDR_WAITING_USERS               6629
#define IDC_PRIORITY_PAUSED             7000
#define IDC_PRIORITY_LOWEST             7001
#define IDC_PRIORITY_LOW                7002
#define IDC_PRIORITY_NORMAL             7003
#define IDC_PRIORITY_HIGH               7004
#define IDC_PRIORITY_HIGHEST            7005
#define IDC_DOWNLOAD_WHOLE_TARGET       7500
#define IDC_REMOVE_SOURCES              8000
#define IDC_DOWNLOAD_FAVORITE_DIRS      8500
#define IDC_DOWNLOAD_WHOLE_FAVORITE_DIRS 9000
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define ID_FILE_QUICK_CONNECT           32777
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define IDC_SEND_MESSAGE                32786
#define IDC_FILTER_FOCUS                32788
#define ID_WINDOW_MINIMIZE_ALL          57654
#define ID_WINDOW_RESTORE_ALL           57655

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1422
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
