//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\Documents\VCProjects\DCPlusPlus\DCPlusPlus.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PROPPAGE_1                  107
#define IDD_GENERALPAGE                 107
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDR_HUB                         129
#define IDC_PUBLIST                     130
#define IDC_HUBLIST                     131
#define IDR_MDIDIRECTORY                132
#define IDC_SERVER                      133
#define IDD_HUBS                        134
#define IDC_FILES                       135
#define IDD_SETTINGS                    201
#define IDB_FOLDERS                     206
#define IDB_ARROWS                      208
#define IDD_PASSWORD                    209
#define IDD_LINE                        209
#define IDB_USERS                       210
#define IDD_PROPPAGE_2                  210
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_UPLOADPAGE                  212
#define IDB_TOOLBAR                     213
#define IDD_APPEARANCEPAGE              213
#define IDR_PUBLICHUBS                  215
#define IDR_SEARCH                      216
#define IDR_FAVORITES                   217
#define IDR_PRIVATE                     218
#define IDR_DIRECTORY                   219
#define IDR_NOTEPAD                     220
#define IDB_TOOLBAR20                   221
#define IDR_QUEUE                       221
#define IDR_SPY                         222
#define IDD_FAVORITEHUB                 223
#define IDR_USERS                       224
#define IDD_ADVANCED2PAGE               224
#define IDB_SPEEDS                      225
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_CONNECTION                  1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1006
#define IDC_PASSIVE                     1007
#define IDC_PORT                        1008
#define IDC_DIRECTORIES                 1009
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_TOTAL                       1014
#define IDC_SLOTS                       1015
#define IDC_SLOTSPIN                    1016
#define IDC_TRANSFERS                   1017
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1018
#define IDC_RESULTS                     1019
#define IDC_PASSWORD                    1019
#define IDC_LINE                        1019
#define IDC_DOWNLOADDIRTO               1020
#define IDC_PRIVATEMESSAGE              1021
#define IDC_VERSION                     1021
#define IDC_GETLIST                     1022
#define IDC_ROLLBACK                    1022
#define IDC_KICK                        1023
#define IDC_CLVERSION                   1023
#define IDC_REDIRECT                    1024
#define IDC_AUTOFOLLOW                  1024
#define IDC_REMOVESOURCE                1025
#define IDC_MODEHELP                    1025
#define IDC_EDIT                        1026
#define IDC_CLEARSEARCH                 1026
#define IDC_NOTEPAD                     1027
#define IDC_FULLROW                     1028
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_REMOVENOTAVAILABLE          1030
#define IDC_SELWINCOLOR                 1031
#define IDC_SELTEXTCOLOR                1032
#define IDC_SELTEXT                     1032
#define IDC_COLOREXAMPLE                1033
#define IDC_SELFONT                     1034
#define IDC_SHAREHIDDEN                 1035
#define IDC_REMOVEFINISHED              1036
#define IDC_QUEUE                       1037
#define IDC_FILTERKICK                  1037
#define IDC_MINIMIZETRAY                1038
#define IDC_OPENPUBLIC                  1039
#define IDC_OPENQUEUE                   1040
#define IDC_HUBNICK                     1041
#define IDC_HUBPASS                     1042
#define IDC_NEWFAV                      1042
#define IDC_HUBNAME                     1043
#define IDC_COMBO1                      1044
#define IDC_AUTOSEARCH                  1045
#define IDC_TIMESTAMPS                  1046
#define IDC_HUBDESCR                    1047
#define IDC_CONFIRMEXIT                 1047
#define IDC_HUBADDR                     1048
#define IDC_IGNOREOFFLINE               1048
#define IDC_GRANTSLOT                   1049
#define IDC_POPUPOFFLINE                1049
#define IDC_FORCE                       1050
#define IDC_REMOVEDUPES                 1050
#define IDC_BUFFERSIZE                  1051
#define IDC_LANGUAGE                    1052
#define IDC_BROWSE                      1053
#define IDC_PUBLIC_HUBS                 1054
#define IDC_THANKS                      1055
#define IDC_DOWNLOADS                   1056
#define IDC_SLOTSSPIN                   1057
#define IDC_MAXSPEED                    1058
#define IDC_SPEEDSPIN                   1059
#define IDC_FAVUSERS                    1060
#define IDC_PROXY                       1060
#define IDC_ADD_TO_FAVORITES            1061
#define IDC_LOG_MAIN_CHAT               1061
#define IDC_COMMENT                     1062
#define IDC_LOG_PRIVATE_CHAT            1062
#define IDC_HELP_HOMEPAGE               1063
#define IDC_LOG_DOWNLOADS               1063
#define IDC_HELP_DOWNLOADS              1064
#define IDC_LOG_UPLOADS                 1064
#define IDC_HELP_REPORT_BUG             1065
#define IDC_LOG_DIRECTORY               1065
#define IDC_HELP_REQUEST_FEATURE        1066
#define IDC_BROWSE_LOG                  1066
#define IDC_HELP_DISCUSS                1067
#define IDC_HELP_HELP_FORUM             1068
#define IDC_HELP_FAQ                    1069
#define IDC_SEARCH_SPY                  1070
#define IDC_IMPORT_QUEUE                1071
#define IDC_LATEST                      1071
#define IDC_PRIVATE_MESSAGE_BEEP        1072
#define IDC_USE_SYSTEM_ICONS            1072
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1073
#define IDC_POPUP_PMS                   1073
#define IDC_STATUS_IN_CHAT              1074
#define IDC_MIN_UPLOAD_SPEED            1074
#define IDC_SHOW_JOINS                  1075
#define IDC_MIN_UPLOAD_SPIN             1075
#define IDC_CHEVRON                     1076
#define IDC_URL_HANDLER                 1076
#define IDC_OPEN_FILE_LIST              1077
#define IDC_TOTALS                      1077
#define IDC_SEARCH                      1078
#define IDC_RATIO                       1078
#define IDC_HELP_README                 1079
#define IDC_POST_DOWNLOAD               1079
#define IDC_CLOSE_WINDOW                1080
#define IDC_POST_UPLOAD                 1080
#define IDC_FIND                        1081
#define IDC_MAIN_CHAT                   1081
#define IDC_NEXT                        1082
#define IDC_PRIVATE_CHAT                1083
#define IDC_FINISHED                    1084
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1084
#define IDC_BROWSETEMPDIR               1085
#define IDC_CHECK1                      1086
#define IDC_REMOVEALL					1087
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define ID_WINDOW_MINIMIZE_ALL          57654

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
