//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\Documents\VCProjects\DCPlusPlus\DCPlusPlus.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_TRAY_QUIT                   102
#define IDC_TRAY_SHOW                   103
#define IDD_GENERALPAGE                 107
#define IDR_MAINFRAME                   128
#define IDR_HUB                         129
#define IDC_HUBLIST                     131
#define IDC_SERVER                      133
#define IDC_FILES                       135
#define IDB_FOLDERS                     206
#define IDB_ARROWS                      208
#define IDD_LINE                        209
#define IDB_USERS                       210
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_UPLOADPAGE                  212
#define IDB_TOOLBAR                     213
#define IDD_APPEARANCEPAGE              213
#define IDR_PUBLICHUBS                  215
#define IDR_SEARCH                      216
#define IDR_FAVORITES                   217
#define IDR_PRIVATE                     218
#define IDR_DIRECTORY                   219
#define IDR_NOTEPAD                     220
#define IDB_TOOLBAR20                   221
#define IDR_QUEUE                       221
#define IDR_SPY                         222
#define IDD_FAVORITEHUB                 223
#define IDR_USERS                       224
#define IDD_ADVANCED2PAGE               224
#define IDD_USER_COMMAND                230
#define IDR_FINISHED_DL                 231
#define IDR_FINISHED_UL                 232
#define IDR_ADLSEARCH                   233
#define IDD_ADLS_PROPERTIES             234
#define IDB_TOOLBAR20_HOT               235
#define IDD_UCPAGE                      236
#define IDR_NET_STATS                   237
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_CONNECTION                  1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1006
#define IDC_PASSIVE                     1007
#define IDC_PORT                        1008
#define IDC_DIRECTORIES                 1009
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_TOTAL                       1014
#define IDC_SLOTS                       1015
#define IDC_SLOTSPIN                    1016
#define IDC_TRANSFERS                   1017
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1018
#define IDC_RESULTS                     1019
#define IDC_LINE                        1019
#define IDC_DOWNLOADDIRTO               1020
#define IDC_PRIVATEMESSAGE              1021
#define IDC_VERSION                     1021
#define IDC_GETLIST                     1022
#define IDC_ROLLBACK                    1022
#define IDC_CLVERSION                   1023
#define IDC_EDIT                        1026
#define IDC_NOTEPAD                     1027
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_SELWINCOLOR                 1031
#define IDC_SELTEXT                     1032
#define IDC_COLOREXAMPLE                1033
#define IDC_SHAREHIDDEN                 1035
#define IDC_QUEUE                       1037
#define IDC_HUBNICK                     1041
#define IDC_HUBPASS                     1042
#define IDC_NEWFAV                      1042
#define IDC_HUBNAME                     1043
#define IDC_SOURCE_TYPE                 1044
#define IDC_SIZE_TYPE                   1045
#define IDC_HUBDESCR                    1047
#define IDC_HUBADDR                     1048
#define IDC_GRANTSLOT                   1049
#define IDC_FORCE                       1050
#define IDC_BUFFERSIZE                  1051
#define IDC_LANGUAGE                    1052
#define IDC_BROWSE                      1053
#define IDC_PUBLIC_HUBS                 1054
#define IDC_THANKS                      1055
#define IDC_DOWNLOADS                   1056
#define IDC_SLOTSSPIN                   1057
#define IDC_MAXSPEED                    1058
#define IDC_SPEEDSPIN                   1059
#define IDC_FAVUSERS                    1060
#define IDC_PROXY                       1060
#define IDC_ADD_TO_FAVORITES            1061
#define IDC_LOG_MAIN_CHAT               1061
#define IDC_LOG_PRIVATE_CHAT            1062
#define IDC_HELP_HOMEPAGE               1063
#define IDC_LOG_DOWNLOADS               1063
#define IDC_HELP_DOWNLOADS              1064
#define IDC_LOG_UPLOADS                 1064
#define IDC_HELP_REPORT_BUG             1065
#define IDC_LOG_DIRECTORY               1065
#define IDC_HELP_REQUEST_FEATURE        1066
#define IDC_BROWSE_LOG                  1066
#define IDC_HELP_DISCUSS                1067
#define IDC_HELP_HELP_FORUM             1068
#define IDC_HELP_FAQ                    1069
#define IDC_SEARCH_SPY                  1070
#define IDC_IMPORT_QUEUE                1071
#define IDC_LATEST                      1071
#define IDC_PRIVATE_MESSAGE_BEEP        1072
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1073
#define IDC_MIN_UPLOAD_SPEED            1074
#define IDC_SETTINGS_TYPE               1074
#define IDC_MIN_UPLOAD_SPIN             1075
#define IDC_CHEVRON                     1076
#define IDC_OPEN_FILE_LIST              1077
#define IDC_TOTALS                      1077
#define IDC_SEARCH                      1078
#define IDC_RATIO                       1078
#define IDC_HELP_README                 1079
#define IDC_POST_DOWNLOAD               1079
#define IDC_CLOSE_WINDOW                1080
#define IDC_POST_UPLOAD                 1080
#define IDC_FIND                        1081
#define IDC_MAIN_CHAT                   1081
#define IDC_NEXT                        1082
#define IDC_PRIVATE_CHAT                1083
#define IDC_FINISHED                    1084
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1084
#define IDC_BROWSETEMPDIR               1085
#define IDC_SOCKS_RESOLVE               1086
#define IDC_REMOVEALL                   1087
#define IDC_HELP_DONATE                 1088
#define IDC_SOCKS5                      1089
#define IDC_SOCKS_SERVER                1090
#define IDC_SOCKS_PORT                  1091
#define IDC_SOCKS_USER                  1092
#define IDC_SOCKS_PASSWORD              1093
#define IDC_FREESLOTS                   1094
#define IDC_COPY_NICK                   1096
#define IDC_ADVANCED_BOOLEANS           1096
#define IDC_ADD_MENU                    1097
#define IDC_MOVE                        1098
#define IDC_REMOVE_MENU                 1098
#define IDC_MENU_ITEMS                  1099
#define IDC_CHANGE_MENU                 1100
#define IDC_NAME                        1101
#define IDC_COMMAND                     1102
#define IDC_HUB                         1103
#define IDC_COMMAND_DESCRIPTION         1105
#define IDC_APPEARANCE_BOOLEANS         1106
#define IDC_DEFAULT_AWAY_MESSAGE        1107
#define IDC_MAX_TAB_ROWS                1107
#define IDC_CLOSE_DISCONNECTED          1108
#define IDC_OPEN_FOLDER                 1109
#define IDC_OPEN_FILE                   1110
#define IDC_FILE_ADL_SEARCH             1111
#define IDC_ADLLIST                     1113
#define IDC_MOVE_UP                     1114
#define IDC_MOVE_DOWN                   1115
#define IDC_HUBUSERDESCR                1116
#define IDC_FINISHED_UL                 1117
#define IDC_SEARCH_STRING               1118
#define IDC_DEST_DIR                    1119
#define IDC_IS_ACTIVE                   1120
#define IDC_MIN_FILE_SIZE               1121
#define IDC_MAX_FILE_SIZE               1122
#define IDC_AUTOQUEUE                   1123
#define IDC_GO_TO_DIRECTORY             1124
#define IDC_MATCH_QUEUE                 1125
#define IDC_HELP_CHANGELOG              1126
#define IDC_VIEW_AS_TEXT                1129
#define IDC_PAGE                        1130
#define IDC_NET_STATS                   1131
#define IDC_SETTINGS_PERSONAL_INFORMATION 1132
#define IDC_SETTINGS_NICK               1133
#define IDC_SETTINGS_EMAIL              1134
#define IDC_SETTINGS_DESCRIPTION        1135
#define IDC_SETTINGS_CONNECTION_TYPE    1136
#define IDC_SETTINGS_CONNECTION_SETTINGS 1137
#define IDC_SETTINGS_IP                 1138
#define IDC_SETTINGS_PORT               1139
#define IDC_SETTINGS_SOCKS5_IP          1140
#define IDC_SETTINGS_SOCKS5_PORT        1141
#define IDC_SETTINGS_SOCKS5_USERNAME    1142
#define IDC_SETTINGS_SOCKS5_PASSWORD    1143
#define IDC_SETTINGS_DIRECTORIES        1144
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1145
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1146
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1147
#define IDC_SETTINGS_DOWNLOADS_MAX      1148
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1149
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1150
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1151
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1152
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1153
#define IDC_SETTINGS_SHARED_DIRECTORIES 1154
#define IDC_SETTINGS_SHARE_SIZE         1155
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1156
#define IDC_SETTINGS_UPLOADS_SLOTS      1157
#define IDC_SETTINGS_COLORS             1158
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1159
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1160
#define IDC_SETTINGS_LANGUAGE_FILE      1161
#define IDC_SETTINGS_REQUIRES_RESTART   1162
#define IDC_SETTINGS_LOGGING            1163
#define IDC_SETTINGS_LOG_DIR            1164
#define IDC_SETTINGS_SOUNDS             1165
#define IDC_SETTINGS_ADVANCED           1166
#define IDC_SETTINGS_ROLLBACK           1167
#define IDC_SETTINGS_CLIENT_VER         1168
#define IDC_SETTINGS_WRITE_BUFFER       1169
#define IDC_SETTINGS_MAX_TAB_ROWS       1170
#define IDC_SETTINGS_USER_MENU          1171
#define IDC_SETTINGS_KB                 1172
#define IDC_SETTINGS_B                  1173
#define IDC_SETTINGS_KBPS               1174
#define IDC_ADD_AS_FAVORITE             1175
#define IDC_SETTINGS_SEPARATOR          1194
#define IDC_SETTINGS_RAW                1195
#define IDC_SETTINGS_CHAT               1196
#define IDC_SETTINGS_PM                 1197
#define IDC_SETTINGS_HUB_MENU           1198
#define IDC_SETTINGS_SEARCH_MENU        1200
#define IDC_SETTINGS_CONTEXT            1201
#define IDC_SETTINGS_PARAMETERS         1202
#define IDC_SETTINGS_NAME               1203
#define IDC_SETTINGS_COMMAND            1204
#define IDC_SETTINGS_HUB                1205
#define IDC_SETTINGS_TO                 1206
#define IDC_RESULT                      1207
#define IDC_REFRESH_FILE_LIST           1210
#define IDC_SETTINGS_ONCE               1212
#define IDC_OPEN_DOWNLOADS              1213
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1214
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1215
#define IDC_COPY_TTH                    1216
#define IDC_SETTINGS_FORMAT1            1217
#define IDC_SETTINGS_FORMAT2            1218
#define IDC_SETTINGS_FORMAT3            1219
#define IDC_SETTINGS_FORMAT4            1220
#define IDC_LOG_SYSTEM                  1221
#define IDC_SEARCH_BY_TTH               1222
#define IDC_SETTINGS_HASH_SPEED         1223
#define IDC_MAX_HASH_SPEED              1223
#define IDC_SETTINGS_MAX_HASH_SPEED     1225
#define IDC_SETTINGS_MBS                1226
#define IDC_BROWSELIST                  3000
#define IDC_REMOVE_SOURCE               3500
#define IDC_PM                          4000
#define IDC_READD                       4500
#define IDC_DOWNLOAD_TARGET             5000
#define IDC_DOWNLOAD_TARGET_DIR         5500
#define IDC_SELECT_WINDOW               6000
#define IDC_USER_COMMAND                6500
#define IDC_PRIORITY_PAUSED             7000
#define IDC_PRIORITY_LOWEST             7001
#define IDC_PRIORITY_LOW                7002
#define IDC_PRIORITY_NORMAL             7003
#define IDC_PRIORITY_HIGH               7004
#define IDC_PRIORITY_HIGHEST            7005
#define IDC_DOWNLOAD_WHOLE_TARGET       7500
#define IDC_REMOVE_SOURCES              8000
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define IDC_SEND_MESSAGE                32786
#define IDC_FILTER_FOCUS                32788
#define ID_WINDOW_MINIMIZE_ALL          57654

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1227
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
