# vim: set filetype=py
 
Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dcpp-bzip', source_glob="*.c", in_bin=False)

ret = env.StaticLibrary(target, sources)

Return('ret')
