#ifndef DCPLUSPLUS_HELP_RESOURCE_H
#define DCPLUSPLUS_HELP_RESOURCE_H

#define IDH_CHANGELOG 500
#define IDH_HUB 501
#define IDH_PM 502
#define IDH_DIRECTORY_LISTING 503
#define IDH_PUBLIC_HUBS 504
#define IDH_FAVORITE_HUBS 505
#define IDH_FAVUSERS 506
#define IDH_QUEUE 507
#define IDH_FINISHED_DL 508
#define IDH_WAITING_USERS 509
#define IDH_FINISHED_UL 510
#define IDH_SEARCH 511
#define IDH_ADL_SEARCH 512
#define IDH_SEARCH_SPY 513
#define IDH_NOTEPAD 514
#define IDH_SYSTEM_LOG 515
#define IDH_NET_STATS 516
#define IDH_HASH_PROGRESS 517
#define IDH_ADVANCED3PAGE 518
#define IDH_ADVANCEDPAGE 519
#define IDH_APPEARANCE2PAGE 520
#define IDH_APPEARANCEPAGE 521
#define IDH_DOWNLOADPAGE 522
#define IDH_UPLOADPAGE 523
#define IDH_FAVORITE_DIRSPAGE 524
#define IDH_GENERALPAGE 525
#define IDH_KEYBOARD 526
#define IDH_LOGPAGE 527
#define IDH_NETWORKPAGE 528
#define IDH_QUEUEPAGE 529
#define IDH_STARTPAGE 530
#define IDH_UCPAGE 531
#define IDH_WINDOWSPAGE 532
#define IDH_CERTIFICATESPAGE 533
#define IDH_TABSPAGE 534

#endif
