# vim: set filetype=py
 
Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dwt', in_bin=False)

env.Append(CPPPATH=["#/dwt/include"])

ret = env.StaticLibrary(target, sources)

Return('ret')

