# vim: set filetype=py
 
Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dcpp-yassl-taocrypt', in_bin=False)

env.Append(CPPPATH=["../include", "../mySTL"])
ret = env.StaticLibrary(target, sources)

dev.env.Append(LIBPATH = [dev.get_build_path(source_path)])

Return('ret')
