# vim: set filetype=py
 
Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'DCPlusPlus')

if 'gcc' in env['TOOLS'] and env['gch']:
    env['Gch'] = env.Gch('stdafx.h')[0]

res = env.RES(dev.get_sources(source_path, '*.rc'))
env.Depends(res, 'resource.h')
sources += res

env.Prepend(LIBS=["comctl32", "ws2_32", "ole32", "gdi32", "comdlg32", "winmm", "shlwapi", "htmlhelp", "oleaut32", "uuid"])
env.Append(CPPPATH=['#/yassl/include', "#/smartwin/include", "#/"])

ret = env.Program(target, [sources, dev.client, dev.zlib, dev.bzip2, dev.yassl, dev.smartwin, dev.boost])
Return('ret')
