# vim: set filetype=py
 
Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'dcpp-smartwin', in_bin=False)

ret = []

ret += dev.build('libs/signals/src/')

Return('ret')

